harproject_app_management_group:
    path:     /
    defaults: { _controller: "HarprojectAppBundle:Management\Group:index" }

harproject_app_management_group_show:
    path:     /{id}/show
    defaults: { _controller: "HarprojectAppBundle:Management\Group:show" }

harproject_app_management_group_new:
    path:     /new
    defaults: { _controller: "HarprojectAppBundle:Management\Group:new" }

harproject_app_management_group_create:
    path:     /create
    defaults: { _controller: "HarprojectAppBundle:Management\Group:create" }
    requirements: { _method: post }

harproject_app_management_group_edit:
    path:     /{id}/edit
    defaults: { _controller: "HarprojectAppBundle:Management\Group:edit" }

harproject_app_management_group_update:
    path:     /{id}/update
    defaults: { _controller: "HarprojectAppBundle:Management\Group:update" }
    requirements: { _method: post|put }

harproject_app_management_group_delete:
    path:     /{id}/delete
    defaults: { _controller: "HarprojectAppBundle:Management\Group:delete" }
    requirements: { _method: get }
