harproject_app_management_member:
    path:     /
    defaults: { _controller: 'HarprojectAppBundle:Management\Member:index' }

harproject_app_management_member_show:
    path:     /{id}/show
    defaults: { _controller: 'HarprojectAppBundle:Management\Member:show' }

harproject_app_management_member_new:
    path:     /new
    defaults: { _controller: 'HarprojectAppBundle:Management\Member:new' }

harproject_app_management_member_create:
    path:     /create
    defaults: { _controller: 'HarprojectAppBundle:Management\Member:create' }
    requirements: { _method: post }

harproject_app_management_member_edit:
    path:     /{id}/edit
    defaults: { _controller: 'HarprojectAppBundle:Management\Member:edit' }

harproject_app_management_member_update:
    path:     /{id}/update
    defaults: { _controller: 'HarprojectAppBundle:Management\Member:update' }
    requirements: { _method: post|put }

harproject_app_management_member_delete:
    path:     /{id}/delete
    defaults: { _controller: 'HarprojectAppBundle:Management\Member:delete' }
    requirements: { _method: get }
