harproject_app_management_relation_type:
    path:     /
    defaults: { _controller: 'HarprojectAppBundle:Management\RelationType:index' }

harproject_app_management_relation_type_show:
    path:     /{id}/show
    defaults: { _controller: 'HarprojectAppBundle:Management\RelationType:show' }

harproject_app_management_relation_type_new:
    path:     /new
    defaults: { _controller: 'HarprojectAppBundle:Management\RelationType:new' }

harproject_app_management_relation_type_create:
    path:     /create
    defaults: { _controller: 'HarprojectAppBundle:Management\RelationType:create' }
    requirements: { _method: post }

harproject_app_management_relation_type_edit:
    path:     /{id}/edit
    defaults: { _controller: 'HarprojectAppBundle:Management\RelationType:edit' }

harproject_app_management_relation_type_update:
    path:     /{id}/update
    defaults: { _controller: 'HarprojectAppBundle:Management\RelationType:update' }
    requirements: { _method: post|put }

harproject_app_management_relation_type_delete:
    path:     /{id}/delete
    defaults: { _controller: 'HarprojectAppBundle:Management\RelationType:delete' }
    requirements: { _method: get }
