harproject_app_management_timetracker:
    path:     /
    defaults: { _controller: "HarprojectAppBundle:Management\TimeTracker:index" }

harproject_app_management_timetracker_show:
    path:     /{id}/show
    defaults: { _controller: "HarprojectAppBundle:Management\TimeTracker:show" }

harproject_app_management_timetracker_new:
    path:     /new
    defaults: { _controller: "HarprojectAppBundle:Management\TimeTracker:new" }

harproject_app_management_timetracker_create:
    path:     /create
    defaults: { _controller: "HarprojectAppBundle:Management\TimeTracker:create" }
    requirements: { _method: post }

harproject_app_management_timetracker_edit:
    path:     /{id}/edit
    defaults: { _controller: "HarprojectAppBundle:Management\TimeTracker:edit" }

harproject_app_management_timetracker_update:
    path:     /{id}/update
    defaults: { _controller: "HarprojectAppBundle:Management\TimeTracker:update" }
    requirements: { _method: post|put }

harproject_app_management_timetracker_delete:
    path:     /{id}/delete
    defaults: { _controller: "HarprojectAppBundle:Management\TimeTracker:delete" }
    requirements: { _method: get }
