harproject_app_management_member:
    resource: "@HarprojectAppBundle/Resources/config/routing/Management/member.yml"
    prefix:   /member

harproject_app_management_group:
    resource: "@HarprojectAppBundle/Resources/config/routing/Management/group.yml"
    prefix:   /group

harproject_app_management_ticket:
    resource: "@HarprojectAppBundle/Resources/config/routing/Management/ticket.yml"
    prefix:   /dashboard/ticket

harproject_app_management_timetracker:
    resource: "@HarprojectAppBundle/Resources/config/routing/Management/timetracker.yml"
    prefix:   /dashboard/timetracker

harproject_app_management_user:
    resource: "@HarprojectAppBundle/Resources/config/routing/Management/user.yml"
    prefix:   /dashboard/user

harproject_app_management_tag:
    resource: "@HarprojectAppBundle/Resources/config/routing/Management/tag.yml"
    prefix:   /dashboard/tag

harproject_app_management_task:
    resource: "@HarprojectAppBundle/Resources/config/routing/Management/task.yml"
    prefix:   /dashboard/task

harproject_app_management_project:
    resource: "@HarprojectAppBundle/Resources/config/routing/Management/project.yml"
    prefix:   /dashboard/project

harproject_app_project:
    resource: "@HarprojectAppBundle/Resources/config/routing/project.yml"
    prefix:   /dashboard/project
    
harproject_app_dashboard_homepage:
    path:   /
    defaults:  { _controller: HarprojectAppBundle:Dashboard:homepage }
    
harproject_app_dashboard_index:
    path:   /dashboard
    defaults:  { _controller: HarprojectAppBundle:Dashboard:index }
    
api_test:
    path:   /api/test
    defaults:  { _controller: HarprojectAppBundle:Api:test }