harproject_app_dashboard_homepage:
    path:   /
    defaults:  { _controller: HarprojectAppBundle:Dashboard:homepage }
    
harproject_app_dashboard_index:
    path:   /dashboard
    defaults:  { _controller: HarprojectAppBundle:Dashboard:index }
  
api_test:
    path:   /api/test
    defaults:  { _controller: HarprojectAppBundle:Api:test }