services:
    #SERVICES
    harproject_app.user:
        class: Harproject\AppBundle\Service\ServiceUser
        arguments: [@service_container]
    harproject_app.group:
        class: Harproject\AppBundle\Service\ServiceGroup
        arguments: [@service_container]
    harproject_app.task:
        class: Harproject\AppBundle\Service\ServiceTask
        arguments: [@service_container]
    harproject_app.timetracker:
        class: Harproject\AppBundle\Service\ServiceTimeTracker
        arguments: [@service_container]
    harproject_app.tag:
        class: Harproject\AppBundle\Service\ServiceTag
        arguments: [@service_container]
    harproject_app.project:
        class: Harproject\AppBundle\Service\ServiceProject
        arguments: [@service_container]
        

    #LISTENERS
    harproject_app.role_listener:
        class: Harproject\AppBundle\Request\HarprojectRoleListener
        arguments: [@annotation_reader, @service_container]
        tags:
            -  { name: kernel.event_listener,  event: kernel.controller, method: onKernelController, priority: -1}
            
    #TWIG
    harproject_app.twig.user:
        class: Harproject\AppBundle\Twig\UserExtension
        arguments: [@service_container]
        tags:
            -  { name: twig.extension}