services:
    harproject_app.user:
        class: Harproject\AppBundle\Service\ServiceUser
        arguments: [@service_container]
    harproject_app.role:
        class: Harproject\AppBundle\Service\ServiceRole
        arguments: [@service_container]
    harproject_app.task:
        class: Harproject\AppBundle\Service\ServiceTask
        arguments: [@service_container]
