services:
    harproject_app.user:
        class: Harproject\AppBundle\Service\ServiceUser
        arguments: [@service_container]
    harproject_app.group:
        class: Harproject\AppBundle\Service\ServiceGroup
        arguments: [@service_container]
    harproject_app.task:
        class: Harproject\AppBundle\Service\ServiceTask
        arguments: [@service_container]
