harproject_app_group:
    path:     /
    defaults: { _controller: "HarprojectAppBundle:Group:index" }

harproject_app_group_show:
    path:     /{id}/show
    defaults: { _controller: "HarprojectAppBundle:Group:show" }

harproject_app_group_new:
    path:     /new
    defaults: { _controller: "HarprojectAppBundle:Group:new" }

harproject_app_group_create:
    path:     /create
    defaults: { _controller: "HarprojectAppBundle:Group:create" }
    requirements: { _method: post }

harproject_app_group_edit:
    path:     /{id}/edit
    defaults: { _controller: "HarprojectAppBundle:Group:edit" }

harproject_app_group_update:
    path:     /{id}/update
    defaults: { _controller: "HarprojectAppBundle:Group:update" }
    requirements: { _method: post|put }

harproject_app_group_delete:
    path:     /{id}/delete
    defaults: { _controller: "HarprojectAppBundle:Group:delete" }
    requirements: { _method: get }
