harproject_app_member:
    path:     /
    defaults: { _controller: "HarprojectAppBundle:Member:index" }

harproject_app_member_show:
    path:     /{id}/show
    defaults: { _controller: "HarprojectAppBundle:Member:show" }

harproject_app_member_new:
    path:     /new
    defaults: { _controller: "HarprojectAppBundle:Member:new" }

harproject_app_member_create:
    path:     /create
    defaults: { _controller: "HarprojectAppBundle:Member:create" }
    requirements: { _method: post }

harproject_app_member_edit:
    path:     /{id}/edit
    defaults: { _controller: "HarprojectAppBundle:Member:edit" }

harproject_app_member_update:
    path:     /{id}/update
    defaults: { _controller: "HarprojectAppBundle:Member:update" }
    requirements: { _method: post|put }

harproject_app_member_delete:
    path:     /{id}/delete
    defaults: { _controller: "HarprojectAppBundle:Member:delete" }
    requirements: { _method: get }
