harproject_app_tag:
    path:     /
    defaults: { _controller: "HarprojectAppBundle:Tag:index" }

harproject_app_tag_show:
    path:     /{id}/show
    defaults: { _controller: "HarprojectAppBundle:Tag:show" }

harproject_app_tag_new:
    path:     /new
    defaults: { _controller: "HarprojectAppBundle:Tag:new" }

harproject_app_tag_create:
    path:     /create
    defaults: { _controller: "HarprojectAppBundle:Tag:create" }
    requirements: { _method: post }

harproject_app_tag_edit:
    path:     /{id}/edit
    defaults: { _controller: "HarprojectAppBundle:Tag:edit" }

harproject_app_tag_update:
    path:     /{id}/update
    defaults: { _controller: "HarprojectAppBundle:Tag:update" }
    requirements: { _method: post|put }

harproject_app_tag_delete:
    path:     /{id}/delete
    defaults: { _controller: "HarprojectAppBundle:Tag:delete" }
    requirements: { _method: get }
