harproject_app_task:
    path:     /
    defaults: { _controller: "HarprojectAppBundle:Task:index" }

harproject_app_task_show:
    path:     /{id}/show
    defaults: { _controller: "HarprojectAppBundle:Task:show" }

harproject_app_task_new:
    path:     /new
    defaults: { _controller: "HarprojectAppBundle:Task:new" }

harproject_app_task_create:
    path:     /create
    defaults: { _controller: "HarprojectAppBundle:Task:create" }
    requirements: { _method: post }

harproject_app_task_edit:
    path:     /{id}/edit
    defaults: { _controller: "HarprojectAppBundle:Task:edit" }

harproject_app_task_update:
    path:     /{id}/update
    defaults: { _controller: "HarprojectAppBundle:Task:update" }
    requirements: { _method: post|put }

harproject_app_task_delete:
    path:     /{id}/delete
    defaults: { _controller: "HarprojectAppBundle:Task:delete" }
    requirements: { _method: get }
