harproject_app_user:
    path:     /
    defaults: { _controller: "HarprojectAppBundle:User:index" }

harproject_app_user_show:
    path:     /{id}/show
    defaults: { _controller: "HarprojectAppBundle:User:show" }

harproject_app_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "HarprojectAppBundle:User:delete" }
    requirements: { _method: get }
